apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: catalog-api
          image: fcg-catalog-api:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__MongoDbConnection
              valueFrom:
                secretKeyRef:
                  name: catalog-secret
                  key: ConnectionStrings__MongoDbConnection

            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: catalog-secret
                  key: jwt-key

            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: catalog-secret
                  key: jwt-issuer

          envFrom:
            - configMapRef:
                name: catalog-config