apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
  namespace: default
type: Opaque
stringData:
  ConnectionStrings__MongoDbConnection: "mongodb://mongodb-catalog:27017/FCGCatalogDB"
  jwt-key: "L9f2QvW8xYp3Zr6TnK1M5D7GhJ0sC4B8UeRtUyVnIqXoPaSdFgHjKlZmN2bVw=="
  jwt-issuer: "SuaAppJwt"